name: Generate OG Image

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Görselde gösterilecek metin'
        required: true
        default: 'Merhaba GitHub Pages'
      filename:
        description: 'Dosya adı (uzantı otomatik .png)'
        required: false
        default: 'og-image'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install canvas
        run: |
          npm init -y
          npm install canvas

      - name: Generate image
        env:
          TEXT: ${{ github.event.inputs.text }}
          FILENAME: ${{ github.event.inputs.filename }}
        run: node scripts/generate.js

      - name: Commit generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add generated/*
          git diff --cached --quiet || git commit -m "Add generated image: ${{ github.event.inputs.filename }}"
          git push
